[package]
name = "manga-updates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
select = "0.6.0"
serde_json = "1.0"
tokio = { version = "0.3", features = ["full"] }